

import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sadiq
 */
public class Booking extends javax.swing.JFrame {
    Connection con;
    Statement st;
  ResultSet rs;
  int CustomerID= 0;
  int Roomid = 0;
  int price;
  String category;
  
    /**
     * Creates new form Booking
     */
    public Booking() {
        initComponents();
        String url="jdbc:mysql://localhost:3306/hotelmanage";
        String user="root";
        String password="root";
        try{
            Class.forName("com.mysql.jdbc.Driver");
                    con=DriverManager.getConnection(url,user,password);
                    st=con.createStatement();
                    System.out.println("Connected");
        }
            catch(Exception e)
                    {
                    System.out.print(e.getMessage());
                    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblRoomCategory = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblRooms = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblCheckIn = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblCheckOut = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblTotalAmount = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        cmbRoomCategory = new javax.swing.JComboBox<>();
        txtPrice = new javax.swing.JTextField();
        txtRooms = new javax.swing.JTextField();
        txtTotalAmount = new javax.swing.JTextField();
        lblRoomId = new javax.swing.JLabel();
        lblCustomerID = new javax.swing.JLabel();
        lblBookingDate = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblRoomIcon = new javax.swing.JLabel();
        lblBookingIcon = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        bookingDate = new com.toedter.calendar.JDateChooser();
        checkinDate = new com.toedter.calendar.JDateChooser();
        checkoutDate = new com.toedter.calendar.JDateChooser();
        txtRoomID = new javax.swing.JTextField();
        txtCustomerID = new javax.swing.JTextField();
        btnSelect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(921, 654));

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 65)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Booking");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hotel.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblRoomCategory.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblRoomCategory.setForeground(new java.awt.Color(204, 204, 204));
        lblRoomCategory.setText("Room Category :");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/list (1).png"))); // NOI18N

        lblPrice.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(204, 204, 204));
        lblPrice.setText("Price   :");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/price-tag.png"))); // NOI18N

        lblRooms.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblRooms.setForeground(new java.awt.Color(204, 204, 204));
        lblRooms.setText("Rooms :");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-room-32.png"))); // NOI18N

        lblCheckIn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCheckIn.setForeground(new java.awt.Color(204, 204, 204));
        lblCheckIn.setText("Check-In :");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-hotel-check-in-32.png"))); // NOI18N

        lblCheckOut.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCheckOut.setForeground(new java.awt.Color(204, 204, 204));
        lblCheckOut.setText("Check-Out :");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-hotel-check-out-32.png"))); // NOI18N

        lblTotalAmount.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTotalAmount.setForeground(new java.awt.Color(204, 204, 204));
        lblTotalAmount.setText("Total Amount :");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-bill-32.png"))); // NOI18N

        btnBook.setBackground(new java.awt.Color(51, 51, 51));
        btnBook.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        btnBook.setForeground(new java.awt.Color(204, 204, 204));
        btnBook.setText("Book");
        btnBook.setEnabled(false);
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        cmbRoomCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category", "Presedential", "Execuetive", "Normal" }));
        cmbRoomCategory.setEnabled(false);

        txtPrice.setBackground(new java.awt.Color(204, 204, 204));
        txtPrice.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtPrice.setEnabled(false);

        txtRooms.setBackground(new java.awt.Color(204, 204, 204));
        txtRooms.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtRooms.setEnabled(false);

        txtTotalAmount.setBackground(new java.awt.Color(204, 204, 204));
        txtTotalAmount.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTotalAmount.setEnabled(false);

        lblRoomId.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblRoomId.setForeground(new java.awt.Color(204, 204, 204));
        lblRoomId.setText("Room ID :");

        lblCustomerID.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCustomerID.setForeground(new java.awt.Color(204, 204, 204));
        lblCustomerID.setText("Customer ID :");

        lblBookingDate.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblBookingDate.setForeground(new java.awt.Color(204, 204, 204));
        lblBookingDate.setText("Booking Date :");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/binary.png"))); // NOI18N

        lblRoomIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/binaryRoom.png"))); // NOI18N

        lblBookingIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/binaryBooking.png"))); // NOI18N

        btnNew.setBackground(new java.awt.Color(51, 51, 51));
        btnNew.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnNew.setForeground(new java.awt.Color(204, 204, 204));
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(51, 51, 51));
        btnCancel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(204, 204, 204));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(51, 51, 51));
        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(204, 204, 204));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        bookingDate.setEnabled(false);

        checkinDate.setEnabled(false);

        checkoutDate.setEnabled(false);

        txtRoomID.setBackground(new java.awt.Color(204, 204, 204));
        txtRoomID.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtRoomID.setEnabled(false);

        txtCustomerID.setBackground(new java.awt.Color(204, 204, 204));
        txtCustomerID.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtCustomerID.setEnabled(false);

        btnSelect.setBackground(new java.awt.Color(51, 51, 51));
        btnSelect.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSelect.setForeground(new java.awt.Color(204, 204, 204));
        btnSelect.setText("Select");
        btnSelect.setEnabled(false);
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(lblBookingIcon)
                            .addComponent(lblRoomIcon)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBookingDate, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRoomId, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblRoomCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCustomerID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblRooms)
                            .addComponent(lblCheckIn)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblCheckOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTotalAmount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(checkoutDate, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(cmbRoomCategory, 0, 250, Short.MAX_VALUE)
                    .addComponent(txtPrice)
                    .addComponent(txtRooms)
                    .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bookingDate, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(checkinDate, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(txtRoomID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCustomerID))
                .addGap(18, 18, 18)
                .addComponent(btnSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(lblBookingIcon)
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel15))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(bookingDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(lblCustomerID)
                                                    .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(11, 11, 11)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lblRoomId)
                                                .addComponent(txtRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lblRoomIcon))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(cmbRoomCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblRoomCategory))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblPrice)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(11, 11, 11)
                                                .addComponent(jLabel6)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtRooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblRooms))
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(checkinDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lblBookingDate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkoutDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalAmount))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 257, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        
        btnSelect.setEnabled(true);
        txtRooms.setEnabled(true);
        btnBook.setEnabled(true);
        btnNew.setEnabled(false);
        bookingDate.setEnabled(true);
        txtCustomerID.setEnabled(true);
        txtRoomID.setEnabled(true);
        txtPrice.setEnabled(true);
        cmbRoomCategory.setEnabled(true);
        txtRooms.setEnabled(true);
        checkinDate.setEnabled(true);
        checkoutDate.setEnabled(true);
        txtTotalAmount.setEnabled(false);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new bookingAddUpdateDelete().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        
        int customerid = Integer.parseInt(txtCustomerID.getText());
        int roomid = Integer.parseInt(txtRoomID.getText());
        String d1, d2, d3;
        String roomcategory="";
        String price = txtPrice.getText();
        String rooms = txtRooms.getText();
        int totalamount;
        
        SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
        
        Date bookdate = bookingDate.getDate();
        Date checkindate = checkinDate.getDate();
        Date checkoutdate = checkoutDate.getDate();
        if(bookdate ==null){
            JOptionPane.showMessageDialog(null,"Please! Select Booking-Date");
            bookingDate.requestFocus();
        }
        else if( txtCustomerID.equals("") ){
            JOptionPane.showMessageDialog(null,"Please Select Customer-ID");
        }
        else if( txtRoomID.equals("") ){
            JOptionPane.showMessageDialog(null,"Please Select Room-ID");
        }
        else if(cmbRoomCategory.getSelectedItem().equals("Select Category")){
            JOptionPane.showMessageDialog(null,"Please Select a Room Category");
           cmbRoomCategory.requestFocus();
        }
        else if(price.equals("")){
            JOptionPane.showMessageDialog(null,"Enter the Room Price");
        }
        else if(rooms.equals("")){
            JOptionPane.showMessageDialog(null,"Provide No. of Rooms");
        }
        else if(checkindate==null){
            JOptionPane.showMessageDialog(null,"Please! Select Checkin-Date");
            checkinDate.requestFocus();
        }
        else if(checkoutdate==null){
            JOptionPane.showMessageDialog(null,"Please! Select Checkout-Date");
            checkoutDate.requestFocus();
        }
        roomcategory = cmbRoomCategory.getSelectedItem().toString();
        d1 = sdf.format(bookdate);
        d2 = sdf.format(checkindate);
        d3 = sdf.format(checkoutdate);

        totalamount = Integer.parseInt(price) * Integer.parseInt(rooms);
        txtTotalAmount.setText(""+totalamount);
        String query = "INSERT INTO bookingdata "
                            + "(bookdate, customerid, roomid, roomcategory, price, rooms, checkindate, checkoutdate, totalamount) "
                            + "VALUES('" + d1 + "','" + customerid + "','"+ roomid +"','" + roomcategory + "','" + price + "','" + rooms + "','" + d2 + "','" + d3 + "','" + totalamount + "')";
                    try{
                    int i=st.executeUpdate(query);
                        JOptionPane.showMessageDialog(null, "Room Booked Successfully");
                        
                    btnSelect.setEnabled(false);
                    btnNew.setEnabled(true);
                    btnBook.setEnabled(false);
                    bookingDate.setEnabled(false);
                    bookingDate.setDate(null);
                    txtCustomerID.setEnabled(false);
                    txtCustomerID.setText("");
                    txtRoomID.setEnabled(false);
                    txtRoomID.setText("");
                    txtRooms.setEnabled(false);
                    txtRooms.setText("");
                    checkinDate.setEnabled(false);
                    checkinDate.setDate(null);
                    checkoutDate.setEnabled(false);
                    checkoutDate.setDate(null);
                    txtTotalAmount.setEnabled(false);
                    txtTotalAmount.setText("");
                    txtPrice.setEnabled(false);
                    txtPrice.setText("");
                    cmbRoomCategory.setEnabled(false);
                    cmbRoomCategory.setSelectedIndex(0);
                    }
                    catch(Exception ex){
                      System.out.print(ex.getMessage());
                    }
            
        
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
         int roomid = Integer.parseInt(txtRoomID.getText());
        String query1 = "select roomid from bookingdata where roomid="+roomid;
         String query2 = "select roomid from roomdetail where roomid="+roomid;
        String query3 = "select price from roomdetail where roomid=" +roomid;
        String query4 = "select category from roomdetail where roomid=" +roomid;
        String query5 = "select rooms from roomdetail where roomid=" +roomid;

        try{
                rs = st.executeQuery(query1);
                if(rs.next()){
                    JOptionPane.showMessageDialog(this, "Room Already Booked");
                    txtRoomID.setText("");
                    cmbRoomCategory.setSelectedIndex(0);
                    txtPrice.setText("");
                    txtRooms.setText("");
            }
            else{
                            try{
                           rs= st.executeQuery(query3);
                           while(rs.next())
                           {
                               int price = rs.getInt("price");
                               txtPrice.setText(String.valueOf(price));
                           }
                                }    
                       catch(Exception e){
                           System.out.println(e.getMessage());
                                           } 
                            
                            try{
                                rs= st.executeQuery(query4);
                                 while(rs.next())
                                     {
                                            String category = rs.getString("category");
                                            cmbRoomCategory.setSelectedItem(category);
                                        }
                                }
                                catch(Exception e){
                                            System.out.println(e.getMessage());
                                }
                            
                            try{
                           rs= st.executeQuery(query5);
                           while(rs.next())
                           {
                               String rooms = rs.getString("rooms");
                               txtRooms.setText(String.valueOf(rooms));
                           }
                                }    
                       catch(Exception e){
                           System.out.println(e.getMessage());
                                           }
            }
        }
        catch(Exception ex){
                    System.out.print(ex.getMessage());
                }
         try{
               rs= st.executeQuery(query2);
                   if(rs.next())
                    {
                      
                    }
                   else{
                   JOptionPane.showMessageDialog(this, "Room Details Not Found!");
                   int option = JOptionPane.showConfirmDialog(null,"Do you want to Add Room Details?");
                             
                   try{
                                if(option==JOptionPane.YES_OPTION)
                                {
                                RoomDetails r = new RoomDetails();
                                r.setVisible(true);
                                this.dispose();
                                }
                                else{
                                   txtRoomID.setText("");
                                }
                            }
                                catch(Exception e){
                                    System.out.print(e.getMessage());
                                }       
                   }
            }
            catch(Exception e){
                  System.out.println(e.getMessage());
                             }
        
    }//GEN-LAST:event_btnSelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser bookingDate;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSelect;
    private com.toedter.calendar.JDateChooser checkinDate;
    private com.toedter.calendar.JDateChooser checkoutDate;
    private javax.swing.JComboBox<String> cmbRoomCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBookingDate;
    private javax.swing.JLabel lblBookingIcon;
    private javax.swing.JLabel lblCheckIn;
    private javax.swing.JLabel lblCheckOut;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblRoomCategory;
    private javax.swing.JLabel lblRoomIcon;
    private javax.swing.JLabel lblRoomId;
    private javax.swing.JLabel lblRooms;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtRoomID;
    private javax.swing.JTextField txtRooms;
    private javax.swing.JTextField txtTotalAmount;
    // End of variables declaration//GEN-END:variables
}
