
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rishabh
 */
public class BookingReport extends javax.swing.JFrame {
    Connection con;
    ResultSet rs;
    Statement st;
    /**
     * Creates new form BookingReport
     */
    public BookingReport() {
        initComponents();
        String url="jdbc:mysql://localhost:3306/hotelmanage";
        String user="root";
        String password="root";
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
                    con=DriverManager.getConnection(url,user,password);
                    st=con.createStatement();
                    System.out.println("Connected");
        }
            catch(Exception e)
                    {
                    System.out.print(e.getMessage());
                    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBookingReport = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBooking = new javax.swing.JTable();
        btnExit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        btnCheck = new javax.swing.JButton();
        btnCheckAll = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mBarBooking = new javax.swing.JMenuBar();
        mHome = new javax.swing.JMenu();
        mItemMaster = new javax.swing.JMenuItem();
        mPrint = new javax.swing.JMenu();
        mItemPrint = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        lblBookingReport.setFont(new java.awt.Font("Times New Roman", 1, 55)); // NOI18N
        lblBookingReport.setForeground(new java.awt.Color(0, 102, 102));
        lblBookingReport.setText("Booking Report");
        jPanel1.add(lblBookingReport);
        lblBookingReport.setBounds(260, 10, 390, 70);

        btnPrint.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrint);
        btnPrint.setBounds(500, 550, 200, 40);

        jScrollPane1.setBorder(null);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblBooking.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tblBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BookDate", "Customer-id", "Room-id", "Category", "Price", "Rooms", "Check-in", "Check-Out", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblBooking.setRowHeight(18);
        tblBooking.setRowMargin(3);
        jScrollPane1.setViewportView(tblBooking);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 190, 910, 290);

        btnExit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(730, 550, 200, 40);

        jPanel2.setForeground(new java.awt.Color(0, 51, 51));

        lblDate.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblDate.setText("         Enter Room id       :");

        btnCheck.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDate)
                .addGap(73, 73, 73)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btnCheck)
                .addGap(251, 251, 251))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheck)
                    .addComponent(txtDate)
                    .addComponent(lblDate))
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(110, 90, 710, 90);

        btnCheckAll.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnCheckAll.setText("Check All Booking");
        btnCheckAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckAllActionPerformed(evt);
            }
        });
        jPanel1.add(btnCheckAll);
        btnCheckAll.setBounds(30, 510, 230, 37);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/background-brown-carpentry-326311.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 930, 630);

        mBarBooking.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mBarBooking.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mBarBooking.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mBarBooking.setMinimumSize(new java.awt.Dimension(90, 40));
        mBarBooking.setPreferredSize(new java.awt.Dimension(157, 36));

        mHome.setText("Home");
        mHome.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        mItemMaster.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        mItemMaster.setText("Master Form");
        mItemMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemMasterActionPerformed(evt);
            }
        });
        mHome.add(mItemMaster);

        mBarBooking.add(mHome);

        mPrint.setText("Print");
        mPrint.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        mItemPrint.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mItemPrint.setText("Print Report");
        mItemPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemPrintActionPerformed(evt);
            }
        });
        mPrint.add(mItemPrint);

        mBarBooking.add(mPrint);

        setJMenuBar(mBarBooking);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
       JOptionPane.showMessageDialog(this,"Report Printed");
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void mItemMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemMasterActionPerformed
        MasterForm call = new MasterForm();
        call.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mItemMasterActionPerformed

    private void mItemPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemPrintActionPerformed
        JOptionPane.showMessageDialog(this, "Report Printed");
    }//GEN-LAST:event_mItemPrintActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        int id = Integer.parseInt( txtDate.getText() );
        String query1= "select * from bookingdata where roomid=" + id;
        String date,category, price, rooms, checkin, checkout;
        int customerid, roomid, amount;
        DefaultTableModel  dm = (DefaultTableModel) tblBooking.getModel();

        int i=0;
        try{
            rs=st.executeQuery(query1);
            dm.setRowCount(0);
            while(rs.next())
            {
                date = rs.getString("bookdate");
                customerid = rs.getInt("customerid");
                roomid = rs.getInt("roomid");
                category = rs.getString("roomcategory");
                price = rs.getString("price");
                rooms= rs.getString("rooms");
                checkin = rs.getString("checkindate");
                checkout = rs.getString("checkoutdate");
                amount = rs.getInt("totalamount");

                i++;

                dm.addRow(new Object[]{date, customerid, roomid, category, price, rooms, checkin, checkout, amount});
            }
            if(i==0)
            {
                JOptionPane.showMessageDialog(null, "Record Not Found");   }
        }
        catch(Exception e)
        {
            System.out.print(e.getMessage());
        }

    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnCheckAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckAllActionPerformed
        
        String query1= "select * from bookingdata";
        String date,category, price, rooms, checkin, checkout;
        int customerid, roomid, amount;
        DefaultTableModel  dm = (DefaultTableModel) tblBooking.getModel();

        int i=0;
        try{
            rs=st.executeQuery(query1);
            dm.setRowCount(0);
            while(rs.next())
            {
                date = rs.getString("bookdate");
                customerid = rs.getInt("customerid");
                roomid = rs.getInt("roomid");
                category = rs.getString("roomcategory");
                price = rs.getString("price");
                rooms= rs.getString("rooms");
                checkin = rs.getString("checkindate");
                checkout = rs.getString("checkoutdate");
                amount = rs.getInt("totalamount");

                i++;

                dm.addRow(new Object[]{date, customerid, roomid, category, price, rooms, checkin, checkout, amount});
            }
            if(i==0)
            {
                JOptionPane.showMessageDialog(null, "Record Not Found");   }
        }
        catch(Exception e)
        {
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_btnCheckAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnCheckAll;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBookingReport;
    private javax.swing.JLabel lblDate;
    private javax.swing.JMenuBar mBarBooking;
    private javax.swing.JMenu mHome;
    private javax.swing.JMenuItem mItemMaster;
    private javax.swing.JMenuItem mItemPrint;
    private javax.swing.JMenu mPrint;
    private javax.swing.JTable tblBooking;
    private javax.swing.JTextField txtDate;
    // End of variables declaration//GEN-END:variables
}
