/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author STUDENT
 */
public class customerAddUpdateDelete extends javax.swing.JFrame {

    /**
     * Creates new form customerAddUpdateDelete
     */
    public customerAddUpdateDelete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnAddicon = new javax.swing.JButton();
        btnUpdateIcon = new javax.swing.JButton();
        btnDeleteIcon = new javax.swing.JButton();
        menuBarAddUpdateDelete = new javax.swing.JMenuBar();
        menuHome = new javax.swing.JMenu();
        mItemMasterForm = new javax.swing.JMenuItem();
        mItemInformation = new javax.swing.JMenu();
        mItemAdd = new javax.swing.JMenuItem();
        mItemUpdate = new javax.swing.JMenuItem();
        mItemRemove = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(921, 654));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setPreferredSize(new java.awt.Dimension(75, 37));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAddicon.setBackground(new java.awt.Color(204, 204, 204));
        btnAddicon.setForeground(new java.awt.Color(204, 204, 204));
        btnAddicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        btnAddicon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddiconActionPerformed(evt);
            }
        });

        btnUpdateIcon.setBackground(new java.awt.Color(102, 102, 102));
        btnUpdateIcon.setForeground(new java.awt.Color(204, 204, 204));
        btnUpdateIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh.png"))); // NOI18N
        btnUpdateIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateIconActionPerformed(evt);
            }
        });

        btnDeleteIcon.setBackground(new java.awt.Color(204, 204, 204));
        btnDeleteIcon.setForeground(new java.awt.Color(204, 204, 204));
        btnDeleteIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/userDelete.png"))); // NOI18N
        btnDeleteIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteIconActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(157, 157, 157)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAddicon, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(btnUpdateIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(btnDeleteIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnBack)
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddicon, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(229, Short.MAX_VALUE))
        );

        menuBarAddUpdateDelete.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        menuBarAddUpdateDelete.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        menuBarAddUpdateDelete.setPreferredSize(new java.awt.Dimension(164, 40));

        menuHome.setText("Home");
        menuHome.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        mItemMasterForm.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
        mItemMasterForm.setText("Master Form");
        mItemMasterForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemMasterFormActionPerformed(evt);
            }
        });
        menuHome.add(mItemMasterForm);

        menuBarAddUpdateDelete.add(menuHome);

        mItemInformation.setText("Information");
        mItemInformation.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        mItemAdd.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
        mItemAdd.setText("Add Customer");
        mItemAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemAddActionPerformed(evt);
            }
        });
        mItemInformation.add(mItemAdd);

        mItemUpdate.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
        mItemUpdate.setText("Update Information");
        mItemUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemUpdateActionPerformed(evt);
            }
        });
        mItemInformation.add(mItemUpdate);

        mItemRemove.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
        mItemRemove.setText("Remove a Customer");
        mItemRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemRemoveActionPerformed(evt);
            }
        });
        mItemInformation.add(mItemRemove);

        menuBarAddUpdateDelete.add(mItemInformation);

        setJMenuBar(menuBarAddUpdateDelete);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        new CustomerPersonalInformation().setVisible(true);
        this.dispose();
             
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
  
     new CustomerUpdate().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        new CustomerDelete().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new MasterForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddiconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddiconActionPerformed
        new CustomerPersonalInformation().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddiconActionPerformed

    private void btnUpdateIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateIconActionPerformed
        // TODO add your handling code here:
        new CustomerUpdate().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUpdateIconActionPerformed

    private void btnDeleteIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteIconActionPerformed
        
        new CustomerDelete().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDeleteIconActionPerformed

    private void mItemRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemRemoveActionPerformed
        new CustomerDelete().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mItemRemoveActionPerformed

    private void mItemAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemAddActionPerformed
        new CustomerPersonalInformation().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mItemAddActionPerformed

    private void mItemMasterFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemMasterFormActionPerformed
        new MasterForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mItemMasterFormActionPerformed

    private void mItemUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemUpdateActionPerformed
        new CustomerUpdate().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mItemUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerAddUpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerAddUpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerAddUpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerAddUpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerAddUpdateDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddicon;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteIcon;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateIcon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mItemAdd;
    private javax.swing.JMenu mItemInformation;
    private javax.swing.JMenuItem mItemMasterForm;
    private javax.swing.JMenuItem mItemRemove;
    private javax.swing.JMenuItem mItemUpdate;
    private javax.swing.JMenuBar menuBarAddUpdateDelete;
    private javax.swing.JMenu menuHome;
    // End of variables declaration//GEN-END:variables
}
