
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sadiq
 */
public class CustomerReport extends javax.swing.JFrame {
    Connection con;
    ResultSet rs;
    Statement st;
    
    /**
     * Creates new form CustomerReport
     */
   
    public CustomerReport() {
        initComponents();
        String url="jdbc:mysql://localhost:3306/hotelmanage";
        String user="root";
        String password="root";
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
                    con=DriverManager.getConnection(url,user,password);
                    st=con.createStatement();
                    System.out.println("Connected");
        }
            catch(Exception e)
                    {
                    System.out.print(e.getMessage());
                    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblCustomerID = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        btnCheck = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        btnPrint = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnCheckAll = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        menuCustomer = new javax.swing.JMenuBar();
        mHome = new javax.swing.JMenu();
        mItemMaster = new javax.swing.JMenuItem();
        mReports = new javax.swing.JMenu();
        mItemBooking = new javax.swing.JMenuItem();
        mPrint = new javax.swing.JMenu();
        mItemPrintReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        jPanel1.setForeground(new java.awt.Color(0, 51, 51));

        lblCustomerID.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblCustomerID.setText("Please Enter Your Customer ID :");

        btnCheck.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(lblCustomerID)
                .addGap(18, 18, 18)
                .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnCheck)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheck)
                    .addComponent(txtCustomerID)
                    .addComponent(lblCustomerID))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(50, 140, 850, 90);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Customer Report");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(260, 50, 440, 70);

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "First Name", "Last Name", "Gender", "Mobile", "Aadhar No.", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCustomer);
        if (tblCustomer.getColumnModel().getColumnCount() > 0) {
            tblCustomer.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblCustomer.getColumnModel().getColumn(6).setPreferredWidth(150);
        }

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(60, 260, 830, 180);

        btnPrint.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrint);
        btnPrint.setBounds(470, 540, 200, 40);

        btnExit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel2.add(btnExit);
        btnExit.setBounds(700, 540, 200, 40);

        btnCheckAll.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnCheckAll.setText("Check All");
        btnCheckAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckAllActionPerformed(evt);
            }
        });
        jPanel2.add(btnCheckAll);
        btnCheckAll.setBounds(60, 480, 140, 37);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/art-art-gallery-art-studio-1931465.jpg"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 10, 930, 630);

        menuCustomer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuCustomer.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuCustomer.setMinimumSize(new java.awt.Dimension(90, 40));
        menuCustomer.setPreferredSize(new java.awt.Dimension(157, 36));

        mHome.setText("Home");
        mHome.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        mItemMaster.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        mItemMaster.setText("Master Form");
        mItemMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemMasterActionPerformed(evt);
            }
        });
        mHome.add(mItemMaster);

        menuCustomer.add(mHome);

        mReports.setText("Reports");
        mReports.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        mItemBooking.setText("Booking");
        mItemBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemBookingActionPerformed(evt);
            }
        });
        mReports.add(mItemBooking);

        menuCustomer.add(mReports);

        mPrint.setText("Print");
        mPrint.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        mItemPrintReport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mItemPrintReport.setText("Print Report");
        mItemPrintReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemPrintReportActionPerformed(evt);
            }
        });
        mPrint.add(mItemPrintReport);

        menuCustomer.add(mPrint);

        setJMenuBar(menuCustomer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
         int id = Integer.parseInt( txtCustomerID.getText() );
        String query1= "select * from customerdata where id=" + id;
        String fname, lname, gender, mobile, aadhar, email;
        DefaultTableModel  dm = (DefaultTableModel) tblCustomer.getModel();
        
        int i=0;
        try{
        rs=st.executeQuery(query1);
        dm.setRowCount(0);
        while(rs.next())
        {
           fname = rs.getString("fname");
               lname = rs.getString("lname");
               gender = rs.getString("gender");
               mobile = rs.getString("mobile");
               aadhar= rs.getString("adhaar");
               email = rs.getString("email");
            
            i++;
            
         dm.addRow(new Object[]{id, fname, lname, gender, mobile, aadhar, email});
        } 
           if(i==0)
       {
            JOptionPane.showMessageDialog(null, "Record Not Found");   }
        }
        catch(Exception e)
        {
             System.out.print(e.getMessage());
        }
        
        
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        JOptionPane.showMessageDialog(this,"Report Printed");
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void mItemMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemMasterActionPerformed
        MasterForm call = new MasterForm();
        call.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mItemMasterActionPerformed

    private void mItemPrintReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemPrintReportActionPerformed
        JOptionPane.showMessageDialog(this, "Report Printed");
    }//GEN-LAST:event_mItemPrintReportActionPerformed

    private void btnCheckAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckAllActionPerformed
        int id ;
        String query1= "select * from customerdata";
        String fname, lname, gender, mobile, aadhar, email;
        DefaultTableModel  dm = (DefaultTableModel) tblCustomer.getModel();
        
        int i=0;
        try{
        rs=st.executeQuery(query1);
        dm.setRowCount(0);
        while(rs.next())
        {
            id = rs.getInt("id");
           fname = rs.getString("fname");
               lname = rs.getString("lname");
               gender = rs.getString("gender");
               mobile = rs.getString("mobile");
               aadhar= rs.getString("adhaar");
               email = rs.getString("email");
            
            i++;
            
         dm.addRow(new Object[]{id, fname, lname, gender, mobile, aadhar, email});
        } 
           if(i==0)
       {
            JOptionPane.showMessageDialog(null, "Record Not Found");   }
        }
        catch(Exception e)
        {
             System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_btnCheckAllActionPerformed

    private void mItemBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemBookingActionPerformed
        new BookingReport().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mItemBookingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnCheckAll;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JMenu mHome;
    private javax.swing.JMenuItem mItemBooking;
    private javax.swing.JMenuItem mItemMaster;
    private javax.swing.JMenuItem mItemPrintReport;
    private javax.swing.JMenu mPrint;
    private javax.swing.JMenu mReports;
    private javax.swing.JMenuBar menuCustomer;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTextField txtCustomerID;
    // End of variables declaration//GEN-END:variables
}
